esphome:
  name: my-new-device
  platform: ESP8266
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "bcce0789d9ddf099920d55621b9f7717"

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "My-New-Device Fallback Hotspot"
    password: "a5aSsOiYW0d4"

captive_portal:


switch:
  - platform: gpio
    name: "Zone 1"
    id: relay_1
    pin: 5
    inverted: true

  - platform: gpio
    name: "Zone 2"
    id: relay_2
    pin: 4
    inverted: true

  - platform: gpio
    name: "Zone 3"
    id: relay_3
    pin: 0
    inverted: true

  - platform: gpio
    name: "Zone 4"
    id: relay_4
    pin: 2
    inverted: true

  - platform: gpio
    name: "Zone 5"
    id: relay_5
    pin: 14
    inverted: true

  - platform: gpio
    name: "Zone 6"
    id: relay_6
    pin: 12
    inverted: true

  - platform: gpio
    name: "Zone 7"
    id: relay_7
    pin: 13
    inverted: true

  - platform: gpio
    name: "Well Pump"
    id: relay_8
    pin: 16
    inverted: true

interval:
  - interval: 15s
    then:
    - if:
        condition:
          wifi.connected:
        then:
        else:
          - switch.turn_off: relay_1
          - switch.turn_off: relay_2
          - switch.turn_off: relay_3
          - switch.turn_off: relay_4
          - switch.turn_off: relay_5
          - switch.turn_off: relay_6
          - switch.turn_off: relay_7
          - switch.turn_off: relay_8